### ISSUE TITLE
Readme/Comments

### ISSUE THREAD

**Issue by rwbc** [OliveriQ/Horowitz#1]
It would be nice if you would add to the readme or comments at least, that you use the Pesto PSTs for evaluation.
https://www.chessprogramming.org/PeSTO%27s_Evaluation_Function

Guenther

**Comment by OliveriQ** [comment]
No problem. Done.

**Comment by rwbc** [comment]
Thanks, that's fine for me. I have added Horowitz now as a new entry in my well-known XB/UCI chronology.
(starting with 2.0 as it makes no sense to add the version before the rewrite anymore)

https://docs.google.com/spreadsheets/d/1GXoy3lGhdKPJbatdw2_2dhWT3TkpthPcNtHs51MQydM
https://docs.google.com/spreadsheets/d/1KWIlXYvEnACeFc4XP3N63pyBSHCG4RqVSCAH22QR1l0

usually reached over my main site
https://rwbc-chess.de/

I am not sure though about your real name. Is it Lucas Oliveri or I am mistaken?
(Note that I don't add anonymous programs, but it is completely up to you if you want to keep your privacy of course)

Guenther (RWBC)

**Comment by OliveriQ** [comment]
Hi, that sounds great! However, I would advise using the latest version
(v2.1.0) that I just recently released, as it's bug free according to my
testing. v2.0.0 makes illegal moves, although rarely. Here's the latest
version (v2.1.0) https://github.com/OliveriQ/Horowitz/releases/tag/v2.1.0.
Yes, my real name is Lucas Oliveri, you can use it. Thanks again!
